### ISSUE TITLE
Behaviour -> Events -> Screens shows no screen names

### ISSUE THREAD

**Issue by Jord-JD** [Daaru00/nwjs-analytics#2]
The section of Google Analytics found at 'Behaviour -> Events -> Screens' shows nothing under the 'Screen Name' column.

I'm using both the `analytics.screenView` and the `analytics.event` methods. So I need to work out  how to tell Analytics which events are associated with which screen. Ideally, it would be great if any events sent were associated with the most recently sent screen view.

It looks like I'm essentially having the same problems as the following URL, but I'm not sure how to apply the suggested fix using your library.

https://stackoverflow.com/questions/30414559/google-analytics-screenname-for-events

Hope you can help!

Many thanks.

**Comment by daaru00** [comment]
Hi, 
I understand your problem but Google Analytics collect event grouped by user session or user id but unfortunately the collect event request  have no "screenView" params. You can check [Google Analytics documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/events). 
The problem is not to be found in the client library but in the Google Analytics data display.
What about using eventCategory as screen view name? 

I saw  'Behaviour -> Events -> Screens' but I don't know how it works, if you find the section in the documentation I will fix it.

**Comment by Jord-JD** [comment]
I figured out how to get the screens associated with events and showing on the 'Behaviour -> Events -> Screens' report in Google Analytics.

It turns out you can simply pass the screenview URL parameter (`cd`) along with the event request. I've modified your library so that it remembers the last screen view request sent and then future event requests will also pass that screen view. This seems to work really well.

Would you be interested in a pull request for this functionality?

**Comment by daaru00** [comment]
Great!
Sure, feel free to make a pull request, thx for your test.
